---

- hosts: databases

  vars:
    database_name: master
    mysql_server_bind_address: "{{ ansible_ens192.ipv4.address }}"
    mysql_server_root_password: <some-password>
    mysql_server_databases:
      - name: "{{ database_name }}"
        encoding: latin1
        collation: latin1_general_ci
    mysql_server_users:
      - name: webdev
        host: "%"
        password: <some-password>
        priv: "master.*:ALL"
  include_role:
    - mysql-server