---

- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
  tags:
    - repo
    - mysql

- include: repo.yml
- include: mysql.yml
