---

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
   - "mysql-community-server={{ mysql_version }}*"
   - "mysql-community-client={{ mysql_version }}*"
   - "mysql-common"
   - "python-mysqldb"
   - "mysql-utilities"
   - "mysqltuner"
  tags:
    - mysql

- name: Tweak systemd file
  when: codename == "jessie" and codename == "stretch"
  register: systemd
  template:
    src: "etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - "mysql.service"
  notify: restart mysql_server
  tags:
    - mysql

- name: Reload systemd files
  when: systemd.changed
  command: "systemctl daemon-reload"
  tags:
    - tomcat

- name: Start and enable MySQL
  service:
    name: mysql
    state: started
    enabled: yes
  tags:
    - mysql

# - name: Include Security Play
#   include: user.yml
#   tags:
#     - sqlsecurity